// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mngmsroqvkaurledgfvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZ21zcm9xdmthdXJsZWRnZnZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg0NzQzOTIsImV4cCI6MjA0NDA1MDM5Mn0.DknANjVk_4WXMlgq-OY9KIFVwyE3W9JHeDdcjlsF6Gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);